# Generated by Django 4.1.7 on 2023-09-13 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('contribuciones', 'Contribuciones efectivas'), ('aportes', 'Aportes sobre nómina')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Gastos',
            },
        ),
        migrations.CreateModel(
            name='infoPlanilla',
            fields=[
                ('numeroPlanilla', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('razonSocial', models.CharField(default='Rama Judicial', max_length=100)),
                ('fecha', models.CharField(default='2023/06', max_length=10)),
                ('identificacion', models.CharField(max_length=100)),
                ('codigoDependenciaSucursal', models.CharField(max_length=100)),
                ('nomDependenciaSucursal', models.CharField(max_length=100)),
                ('fechaReporte', models.DateField()),
                ('fechaLimitePago', models.DateField()),
                ('periodoPension', models.CharField(max_length=7)),
                ('periodoSalud', models.CharField(max_length=7)),
                ('totalCotizantes', models.IntegerField()),
                ('PIN', models.CharField(max_length=100)),
                ('tipoPlanilla', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Información Planillas',
            },
        ),
        migrations.CreateModel(
            name='Patronal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('temporal', 'Temporal'), ('permanente', 'Permanente')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Patronales',
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('codigo', models.CharField(default='COD', max_length=50, primary_key=True, serialize=False)),
                ('NIT', models.CharField(max_length=50)),
                ('concepto', models.CharField(max_length=100)),
                ('razonEntidad', models.CharField(max_length=100)),
                ('rubroPermanente', models.CharField(max_length=100)),
                ('rubroTemporal', models.CharField(max_length=100)),
                ('tipoCuentaPagar', models.CharField(max_length=100)),
                ('codigoDescuento', models.CharField(default='COD', max_length=100)),
                ('tipo', models.CharField(default='tipo', max_length=100)),
                ('idTipoGasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_upload.gasto')),
            ],
            options={
                'verbose_name_plural': 'Entidades',
            },
        ),
        migrations.CreateModel(
            name='valoresPlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIT', models.CharField(max_length=50)),
                ('numeroAfiliados', models.IntegerField()),
                ('fondoSolidaridad', models.IntegerField(default=0)),
                ('fondoSubsistencia', models.IntegerField(default=0)),
                ('totalIntereses', models.IntegerField(default=0)),
                ('valorPagarSinIntereses', models.IntegerField(default=0)),
                ('valorPagar', models.IntegerField(default=0)),
                ('codigoEntidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_upload.entidad')),
                ('numeroPlanilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_upload.infoplanilla')),
            ],
            options={
                'verbose_name_plural': 'Valores Planilla',
                'unique_together': {('numeroPlanilla', 'codigoEntidad')},
            },
        ),
        migrations.CreateModel(
            name='valoresPatron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=10)),
                ('unidad2', models.IntegerField(default=0)),
                ('unidad8', models.IntegerField(default=0)),
                ('unidad9', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('NIT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_upload.entidad')),
                ('tipoPatronal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_upload.patronal')),
            ],
            options={
                'verbose_name_plural': 'Valores Patrón',
                'unique_together': {('NIT', 'tipoPatronal', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='valoresEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=10)),
                ('unidad', models.IntegerField()),
                ('numDoc', models.CharField(max_length=30)),
                ('saldo', models.IntegerField(default=0)),
                ('NIT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_upload.entidad')),
            ],
            options={
                'verbose_name_plural': 'Valores Empleados',
                'unique_together': {('NIT', 'numDoc', 'fecha')},
            },
        ),
    ]
