# Generated by Django 4.1.7 on 2023-07-25 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('NIT', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('concepto', models.CharField(max_length=100)),
                ('razonEntidad', models.CharField(max_length=100)),
                ('rubro', models.CharField(max_length=100)),
                ('tipoCuentaPagar', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('contribuciones', 'Contribuciones efectivas'), ('aportes', 'Aportes sobre nómina')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patronal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('temporal', 'Temporal'), ('permanente', 'Permanente')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad2', models.IntegerField()),
                ('unidad8', models.IntegerField()),
                ('unidad9', models.IntegerField()),
                ('total', models.IntegerField()),
                ('NIT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_upload.entidad')),
                ('idPatronal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_upload.patronal')),
            ],
        ),
        migrations.AddField(
            model_name='entidad',
            name='idTipoGasto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_upload.gasto'),
        ),
    ]
